Update mediatum dependencies: nixpkgs-23.11pre496033.c1bca7fe84c (#3295)
old:                                new:
nginx-1.20.2                        nginx-1.24.0
postgresql-14.1                     postgresql-14.8
uwsgi-2.0.20                        uwsgi-2.0.20
acme.sh-3.0.2                       acme.sh-3.0.6
ffmpeg-4.4.1-bin                    ffmpeg-5.1.3-bin
ghostscript-9.55.0                  ghostscript-with-X-10.01.1
graphicsmagick-1.3.37               graphicsmagick-1.3.39
graphviz-2.49.3                     graphviz-7.1.0
pdftk-3.3.2                         pdftk-3.3.3
poppler-utils-22.01.0               poppler-utils-23.02.0
icu4c-70.1-dev                      icu4c-73.1-dev
perl5.34.0-Image-ExifTool-12.39     perl5.36.0-Image-ExifTool-12.62

Due to glibc dependencies of uwsgi, uwsgi can only be build with
nixpkgs-22.05pre363272.4d600814942 where
/nix/store/q29bwjibv9gi9n86203s38n0577w09sx-glibc-2.33-117 is used by
uwsgi.

Newer versions of glibc prevents the start of uwsgi with:

  File "./utils/utils.py", line 34, in <module>
    from lxml import etree
ImportError: /nix/store/6w8g7njm4mck5dmjxws0z1xnrxvl81xa-glibc-2.34-115/lib/libpthread.so.0:
version `GLIBC_PRIVATE' not found (required by
/nix/store/hnp72ygssavd526rp7qk3yjylyc2klcw-glibc-2.27/lib/librt.so.1)